version: '3.5'

services:
  api:
    image: k0walski/presse_idependante_gwendhal_claudel_api:latest
    container_name: api
    build: .
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: ${MONGO_HOST}
      DEBUG_LEVEL: ${DEBUG_LEVEL}
    working_dir: /usr/src/app
    user: ${CURRENT_UID}
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
    - $PWD/data/db:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:27017" ]
      interval: 10s
      timeout: 5s
      retries: 5